services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: tom
      POSTGRES_PASSWORD: SuperSecret7!
      POSTGRES_DB: RememberDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  userapi:
    build: 
      context: .
      dockerfile: "WebApplication1/Dockerfile"
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - CONNECTION_STRING=Host=db;Port=5432;Username=tom;Password=SuperSecret7!;Database=RememberDb

volumes:
  pgdata:
